# This is a basic workflow to help you get started with Actions

name: Add end date

# Controls when the workflow will run
on:
  # Triggers the workflow on closed issues
  issues:
    types:
      - closed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
      - name: Change end date in project
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_ID: ${{ github.event.issue.id }}
          FIELD_ID: 231893718
          PROJECT_ID: 1
          CURRENT_DATE: ${{ steps.date.outputs.date }}
          
        run: |
          gh project item-edit --id $ISSUE_ID --field-id $FIELD_ID --project-id $PROJECT_ID --text $CURRENT_DATE
